SMTP_MAIL_USEPASSWORD: true
SMTP_MAIL_USERNAME: vapidpromotions
SMTP_MAIL_PASSWORD: md-n8EsGIhYJE2KAQQ-uo8PRg
SMTP_MAIL_HOSTNAME: smtp.mandrillapp.com
SMTP_MAIL_PORT: 587

twitter:
    consumerKey: YS9ZsLmfjsDOPdFXEBeo4dqRI
    consumerSecret: 5jCQn9Gpg1G6dOwPVnZ4rnvS12K5gWi5p7nBf0hlerphhCKkFU
    accessToken: 1511798514535346188-awV7RbNV470h4h4ThrzYImy7viCcc1
    accessTokenSecret: qRjOyEqkbxFhrW6TY9VVml6Zc2fSdV6XdBf2GAQth8LPW
net:
  sf:
    jasperreports:
      export:
        pdf:
          user:
            password: X1smokInvoice1X

Majorana:
  lockout:
    period:
      minutes: 90
  max:
    login:
      attempts: 5


Majorana_AWS_REGION: eu-west-3
SESSION_REDIS_HOST: 192.168.1.76
SESSION_REDIS_PASSWORD: redis10123
SESSION_REDIS_TIMEOUT:  2000

stripe_api_key:

spring:
  web:
    resources:
      :static-locations: classpath:static/images
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.cassandra.CassandraDataAutoConfiguration

  devtools:
    restart:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 41943040
  session:
    timeout: 60m
  thymeleaf:
    cache: false
    mode: HTML
  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    serialization:
      write_dates_as_timestamps: false



management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: false
      show-details: never
  health:
    defaults:
      enabled: false
    db:
      enabled: false

logging:
  level:
    ROOT: debug
    org:
       springframework:
         web:
            servlet:
              mvc: DEBUG
    com.smokpromotion: debug
    org.javers: warn
  file:
    name: /usr/tomcat9/logs/spring.log

smok:
  admin:
    version: 0.1.0
  app:
    version: 0.1.0
  demon:
    version: 0.1.0
  init:
    version: 0.1.0
  searchrunner:
    version: 0.1.0
smok_db:
  cass1:
    name: smokCass
    enabled: false
    remoteDatabaseNameAtService: cassandra
    username: smok_cass1
    password: SqlDev7!
    isolationLevel: noTransactions
    dbVariant: cassandra
    hostAddress: 192.168.1.76
    Port: 7000
    port: 9042
    priority: 1
    group: SmokCluster
    useSSL: false
    verifySSL: false
  mysql:
    name: mysql
    enabled: true
    username: promo
    remoteDatabaseNameAtService: promo
    password: PromoAskHow7!
    isolationLevel: noTransactions
    dbVariant: mysql
    group: "promo"
    hostAddress: 127.0.0.1
    #    Port: 7000
    port: 3306
    priority: 2
    useSSL: false
    verifySSL: false

server:
  tomcat
    :accept-count=100
    :max-connections=10000
    :threads=200
    :min-spare-threads=10
    :max-swallow-size=2MB
    :max-http-post-size=2MB
  error
    :include-message=always
---
spring.config.activate.on-profile: smok_admin
server:
  port: 9202
---
spring.config.activate.on-profile: smok_app
server:
  port: 9201
---
spring.config.activate.on-profile: smok_demon
server:
  port: 9203
---
spring.config.activate.on-profile: smok_init
server:
  port: 9204
---
spring.cache.type=redis
spring.redis.host=192.168.1.75
spring.redis.port=6379
spring.redis.password=redis10123
