
net:
  sf:
    jasperreports:
      export:
        pdf:
          user:
            password: X1smokInvoice1X
  Majorana_AWS_REGION: eu-west-3
spring:
  flyway:
    #baseline-on-migrate: true
    #enabled: true
    baseline-on-migrate: false
    enabled: false
    locations: "classpath: db_migrations"
    url: jdbc:mysql://localhost:3306/mysql
    schemas: smok
    user: "smok"
    password: "SmokSql7!"
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 41943040
  session:
    timeout: 60m
  thymeleaf:
    cache: false
    mode: HTML
  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
  health:
    defaults:
      enabled: false
    db:
      enabled: false

endpoints:
  enabled: false
  health:
    enabled: false
  metrics:
    enabled: false
logging:
  level:
    ROOT: debug
    com.com.smokpromotion: debug
    org.javers: warn

smok:
  admin:
    version: 0.1.0
  app:
    version: 0.1.0
  demon:
    version: 0.1.0
  init:
    version: 0.1.0
  searchrunner:
    version: 0.1.0
smok-db:
#  cass1:
#    name: smokCass
#    remoteDatabaseNameAtService: cassandra
#    username: smok_cass1
#    password: SqlDev7!
#    isolationLevel: noTransactions
#    dbVariant: cassandra
#    hostAddress: 192.168.1.76
#    Port: 7000
#    port: 9042
#    priority: 1
#    group: SmokCluster
#    useSSL: false
#    verifySSL: false
  mysql:
    name: mysql
    username: promo
    remoteDatabaseNameAtService: mysql
    password: PromAskHow7!
    isolationLevel: noTransactions
    dbVariant: mysql
    group: "smok"
    hostAddress: 127.0.0.1
    #    Port: 7000
    port: 3306
    priority: 2
    useSSL: false
    verifySSL: false

---
spring.config.activate.on-profile: admin
server:
  port: 9002
---
spring.config.activate.on-profile: smok-app
server:
  port: 9001
---
spring.config.activate.on-profile: smok-demon
server:
  port: 9003
---
spring.config.activate.on-profile: init
server:
  port: 9004
