smok:
  admin:
    version: 0.1.0
  app:
    version: 0.1.0
  demon:
    version: 0.1.0
  init:
    version: 0.1.0
  searchrunner:
    version: 0.1.0
smok-db:
  cass1:
    Name: smok
    Username: smok_cass1
    IsolationLevel: noTransactions
    DbVariant: cassandra
    HostAddress: 127.0.0.1
#    Port: 7000
    Port: 9042
    Priority: 1
    Group: SmokCluster
    UseSSL: false
    VerifySSL: false
  mysql1:
    Name: smok
    Username: smok_cass1
    IsolationLevel: noTransactions
    DbVariant: mysql
    HostAddress: 127.0.0.1
    #    Port: 7000
    Port: 3033
    Priority: 2
    UseSSL: false
    VerifySSL: false
