flyway:
  url: jdbc:mysql://localhost:3306/mysql
  schemas: smok
  user: "smok"
  password: "SmokSql7!"

net:
  sf:
    jasperreports:
      export:
        pdf:
          user:
            password: X1smokInvoice1X

spring:
  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: "classpath: db_migrations"
  jpa:
    hibernate:
      ddl-auto: validate
  servlet:
    multipart:
      max-file-size: 10485760
      max-request-size: 41943040
  session:
    timeout: 60m
  thymeleaf:
    cache: false
    mode: HTML
  messages:
    basename: messages
    encoding: UTF-8
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never
  health:
    defaults:
      enabled: false
    db:
      enabled: false

endpoints:
  enabled: false
  health:
    enabled: false
  metrics:
    enabled: false
logging:
  level:
    ROOT: info
    com.urcompliant: debug
    org.javers: warn

smok:
  admin:
    version: 0.1.0
  app:
    version: 0.1.0
  demon:
    version: 0.1.0
  init:
    version: 0.1.0
  searchrunner:
    version: 0.1.0
smok-db:
  cass1:
    name: smokCass
    username: smok_cass1
    passwd: SqlDev7!
    isolationLevel: noTransactions
    dbVariant: cassandra
    hostAddress: 127.0.0.1
#    Port: 7000
    port: 9042
    priority: 1
    group: SmokCluster
    useSSL: false
    verifySSL: false
  mysql1:
    name: smokMysql
    username: smok
    oasswd: SmokSql7!
    isolationLevel: noTransactions
    dbVariant: mysql
    hostAddress: 127.0.0.1
    #    Port: 7000
    port: 3306
    priority: 2
    useSSL: false
    verifySSL: false

---
spring.config.activate.on-profile: admin
server:
  port: 9002
---
spring.config.activate.on-profile: app
server:
  port: 9001
---
spring.config.activate.on-profile: demon
server:
  port: 9003
---
spring.config.activate.on-profile: init
server:
  port: 9004
